### ISSUE TITLE
how to read sms from central sms database in blackberry10 cordova

### ISSUE THREAD

**Issue by DILEEP-YADAV** [shikhirsingh/SMS-BB10-Cordova-Plugin#1]
@shikhirsingh  HI! Can u help me ? about , how to read sms from central sms database in blackberry10 cordova plugin

**Comment by shikhirsingh** [comment]
Dileep, I am no longer part of this project. I believe this is possible thought. If I were you, I'd check if the BES already has capability to do this for you.

**Comment by shikhirsingh** [comment]
Also, look at this. This has everything you need to build the app:
https://supportforums.blackberry.com/t5/Native-Development-Knowledge/BlackBerry-10-Developer-s-Guide-to-SMS-and-MMS/ta-p/2497239

**Comment by DILEEP-YADAV** [comment]
@shikhirsingh  thanks, I will try
